FROM ruby:3.2.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN gem install bundler
WORKDIR /backend
COPY ./backend/Gemfile ./Gemfile
RUN bundle install
COPY ./backend .
COPY ../entrypoint.sh /usr/bin/
COPY entrypoint.sh /usr/bin/
RUN apt-get update && apt-get install -y dos2unix && dos2unix /usr/bin/entrypoint.sh && chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]
EXPOSE 3000
CMD ["rails", "server", "-b", "0.0.0.0"]