# Stage 1: Build the Angular application
FROM node:latest AS build
WORKDIR /frontend
COPY ./frontend/package.json ./
RUN yarn install
COPY ./frontend .
RUN yarn run build

# Stage 2: Serve the application from Nginx
FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=build /frontend/dist/frontend /usr/share/nginx/html/browser
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod -R 755 /usr/share/nginx/html/browser
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]